### ISSUE TITLE
FIX: make footer stick to the bottom of the page

### ISSUE THREAD

**Issue by Tomer51m** [haifa-dev/official-website#36]
Footer should stay at the bottom of the page, even if there is little content.

**Comment by Danex2** [comment]
Can I attempt this one?

**Comment by haifa-dev** [comment]
> Can I attempt this one?

sure 🙂

**Comment by Tomer51m** [comment]
> Can I attempt this one?

Sure 🙂

**Comment by Danex2** [comment]
> 
> 
> > Can I attempt this one?
> 
> Sure 🙂
Seems I need permission to push the change, let me know when I can :)

**Comment by Polarts** [comment]
Hi @Danex2, thanks for helping us out!
To work on this issue, please fork our repo and make your changes. Once you're done, go to the "Pull Requests" tab and reate one with a matching title. We'll review your code and request any changes if needed :)
