### ISSUE TITLE
Add descriptions to request form's fields

### ISSUE THREAD

**Issue by Polarts** [haifa-dev/official-website#43]
Some of the form's fields are too complicated to understand just by the title, so we should add some description.

I think the cleanest way would be making it a [hover-tooltip](https://react-bootstrap.github.io/components/overlays/) popping out of a [help icon](https://materialdesignicons.com/).
Hover actions should work as taps in touch devices.

**Comment by cHidoriPunk** [comment]
can you assign this to me please ?

**Comment by cHidoriPunk** [comment]
done
